In [23]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns

In [24]:
df = pd.read_csv('C:/Users/nguye/SteamCrawler/Preprocessing/SteamGames.csv')

### Do vấn đề về việc cào không liên tục (cào trong nhiều đợt ngắt quãng) do trang web chặn, nên bị trùng xếp hạng về độ phổ biến, giờ ta phải xử lí lại đễ rank được liên tục

In [25]:
display(df[df['Rank'] == 1])

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank
0,3764200,Resident Evil Requiem,game,"Feb 26, 2026","Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,9,23715,793,NaN,NaN,NaN,1
13212,4418930,The Bazaar - Karnok,dlc,"Mar 4, 2026",Strategy,Tempo,NaN,The Monstrous Hunter Expansion adds over 120 n...,19.99$,https://shared.akamai.steamstatic.com/store_it...,"Strategy,Auto Battler,Deckbuilding,Card Battle...",0,7,0,Windows 10 (64-bit),3 GB RAM,AMD 2.4GHz 2-Core or Intel i3 2.4GHz 2-Core,1

In [26]:
df['Rank'] = np.arange(1, len(df) + 1)

In [27]:
display(df[df['Rank'] == 1])

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank
0,3764200,Resident Evil Requiem,game,"Feb 26, 2026","Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,9,23715,793,NaN,NaN,NaN,1

In [28]:
# Vậy ta đã xử lí xong việc bị trùng lại rank do việc cào ngắt quãng

### Xử lí dữ liệu bị NULL

In [29]:
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate            14
Genres                413
Developers             26
Publishers           1045
Description            52
price                   0
Thumbnail               0
Tags                 1614
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement        2937
MemoryRequirement    3984
CpuRequirement       3859
Rank                    0
dtype: int64

In [30]:
# Những ngày tháng không không hợp lệ sẽ được loại bỏ, với số lượng không đáng kể 
df.dropna(subset=['ReleaseDate'], inplace=True)

In [31]:
# Với cột dev và publisher, qua quá trình đọc hiểu dữ liệu, nhận thấy thường thì dev và publisher sẽ là một, hoặc có thể có nhiều dev nhưng chỉ có một publisher. 
df["Publishers"]= df["Publishers"].fillna(df["Developers"])
df['Developers'] = df['Developers'].fillna(df['Publishers'])

In [32]:
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate             0
Genres                411
Developers             11
Publishers             11
Description            52
price                   0
Thumbnail               0
Tags                 1610
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement        2929
MemoryRequirement    3976
CpuRequirement       3851
Rank                    0
dtype: int64

In [33]:
# Có thể thấy số null của cột developers và publishers là bằng nhau, với số lượng không đáng kể, những game không rõ nguồn gốc ta sẽ không đề xuất cho mọi người nên dev và pub cùng null ta sẽ bỏ 
df.dropna(subset=['Developers'], inplace=True)
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate             0
Genres                406
Developers              0
Publishers              0
Description            50
price                   0
Thumbnail               0
Tags                 1603
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement        2923
MemoryRequirement    3970
CpuRequirement       3844
Rank                    0
dtype: int64

In [34]:
display(df[df['Description'].isnull()])

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank
44,2357570,Overwatch®,game,"Aug 10, 2023","Action,Free To Play","Blizzard Entertainment, Inc.","Blizzard Entertainment, Inc.",NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Free to Play,Hero Shooter,FPS,Multiplayer,Team...",5,64,72,Windows® 10 64-bit (latest Service Pack),6 GB RAM,Intel® Core™ i3 or AMD Phenom™ X3 8650,45
107,1771300,Kingdom Come: Deliverance II,game,"Feb 4, 2025","Action,Adventure,RPG",Warhorse Studios,Deep Silver,NaN,59.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,8,56046,4051,NaN,NaN,NaN,108
162,3932890,Escape from Tarkov,game,"Nov 15, 2025","Action,Massively Multiplayer,RPG,Simulation",Battlestate Games,Battlestate Games,NaN,49.99$,https://shared.akamai.steamstatic.com/store_it...,"Extraction Shooter,Shooter,Gun Customization,T...",5,5562,3689,Windows 10,16 GB RAM,AMD Ryzen 5 3600 or similar,163
166,2138330,Cyberpunk 2077: Phantom Liberty,dlc,"Sep 25, 2023",RPG,CD PROJEKT RED,CD PROJEKT RED,NaN,29.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,8,9365,916,NaN,NaN,NaN,167
239,9900,Star Trek Online,game,"Jan 31, 2012","Massively Multiplayer,RPG,Free To Play",Cryptic Studios,Arc Games,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Free to Play,Sci-fi,Massively Multiplayer,Spac...",6,642,198,NaN,NaN,NaN,240
907,3368610,Kingdom Come: Deliverance II Legacy of the Forge,dlc,"Sep 9, 2025","Action,Adventure,RPG",Warhorse Studios,Deep Silver,NaN,13.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,5,488,225,NaN,NaN,NaN,908
916,1574820,Until Then,game,"Jun 25, 2024","Adventure,Casual,Indie",Polychroma Games,Maximum Entertainment,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Emotional,Pixel Graphics,Story Ri...",9,7600,162,Windows 7,4 GB RAM,Intel Core i5-4460 / AMD FX-8320,917
999,109600,Neverwinter,game,"Dec 5, 2013","Action,Adventure,Massively Multiplayer,RPG,Fre...",Cryptic Studios,Arc Games,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Free to Play,MMORPG,RPG,Massively Multiplayer,...",5,75,33,Windows® 10/11 (64-bit),4 GB RAM,Core 2 Duo 2.2Ghz (or equivalent AMD CPU),1000
1072,3368620,Kingdom Come: Deliverance II Mysteria Ecclesiae,dlc,"Nov 11, 2025","Action,Adventure,RPG",Warhorse Studios,Deep Silver,NaN,13.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,5,334,253,NaN,NaN,NaN,1073
1134,2067050,Squirrel with a Gun,game,"Aug 29, 2024","Action,Adventure,Indie,Simulation",Dee Dee Creations LLC,Maximum Entertainment,NaN,6.99$,https://shared.akamai.steamstatic.com/store_it...,"Action,Simulation,Third-Person Shooter,Sandbox...",8,2127,333,Windows 7 (64 bit),8 GB RAM,2.6 GHz,1135
1152,2366980,Thank Goodness You're Here!,game,"Aug 1, 2024","Adventure,Casual,Indie",Coal Supper,Panic,NaN,11.99$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Comedy,Funny,Hand-drawn,Exploration,...",9,5224,185,10,4 GB RAM,Intel Core2 Duo E6750 or AMD Athlon 64 X2 6400+,1153
1545,584400,Sonic Mania,game,"Aug 29, 2017","Action,Adventure,Casual","Christian Whitehead,Headcannon,PagodaWest Games",SEGA,NaN,19.99$,https://shared.akamai.steamstatic.com/store_it...,"Great Soundtrack,2D,Platformer,Retro,Classic,P...",8,12816,909,Windows 7 / 8 / 10,2 GB RAM,Core 2 Duo,1546
3536,1953520,WRC Generations – The FIA WRC Official Game,game,"Nov 3, 2022","Racing,Simulation",KT Racing,Nacon,NaN,7.99$,https://shared.akamai.steamstatic.com/store_it...,"Racing,Simulation,Realistic,Multiplayer,PvP,Co...",5,635,335,Windows 10,8 GB RAM,Intel Core i5-2300 or AMD FX-6300,3537
3909,1776790,DRUDGE,game,"Jan 15, 2026","Action,Indie,Simulation,Early Access",Writegg,Writegg,NaN,12.99$,https://shared.akamai.steamstatic.com/store_it...,"Simulation,Action,Life Sim,Dungeon Crawler,Exp...",8,70,3,Windows 10 (64-bit),4 GB RAM,Intel Core i5 or AMD equivalent,3910
4130,1199030,Tainted Grail: Conquest,game,"May 27, 2021","Action,Indie,RPG",Questline,Awaken Realms,NaN,19.99$,https://shared.akamai.steamstatic.com/store_it...,"Deckbuilding,Card Game,Dark Fantasy,Roguelike,...",8,3749,432,Windows 7/8/10 64-bit,8 GB RAM,3.2 GHz Dual Core Processor,4131
4214,1520470,Soul Dossier,game,"Mar 29, 2021","Action,Adventure,Massively Multiplayer,RPG,Str...",GKD GAME,GKD GAME,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Sexual Content,Nudity,Free to Play,Mature,Hent...",0,0,0,"Windows 7, Windows 8.1,Windows10",6 GB RAM,Intel I5 8400 /AMD Ryzen5 1500X,4215
5084,1282410,Hard West 2,game,"Aug 4, 2022","Action,RPG,Strategy",Ice Code Games,Good Shepherd Entertainment,NaN,29.99$,https://shared.akamai.steamstatic.com/store_it...,"Turn-Based Strategy,Western,Turn-Based Tactics...",8,1048,234,Windows 10 (64bit),8 GB RAM,Intel Core 2 Duo E4700 2.6 GHz/AMD Phenom 9950...,5085
5221,3620940,Sushi Cat Legacy Collection,game,"Nov 10, 2025",Strategy,Armor Games Studios,Armor Games Studios,NaN,4.99$,https://shared.akamai.steamstatic.com/store_it...,"Strategy,Old School,Colorful,Cats,Casual,Arcad...",8,130,4,Windows 10 or newer,4 GB RAM,2.0 GHz Dual Core,5222
5302,1018800,DEEEER Simulator: Your Average Everyday Deer Game,game,"Nov 23, 2021","Action,Casual,Indie,Simulation",Gibier Games,PLAYISM,NaN,14.99$,https://shared.akamai.steamstatic.com/store_it...,"Exploration,Sandbox,Physics,Funny,Third Person...",8,1845,108,Windows 7 or Newer,2 MB RAM,Core i3-3120M,5303
5767,1044620,Aokana - Four Rhythms Across the Blue,game,"Sep 27, 2019","Adventure,Casual","sprite,NekoNyan Ltd.","NekoNyan Ltd.,HIKARI FIELD",NaN,34.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Anime,Casual,Story Rich,Romance,A...",9,787,24,Windows 7 or newer,4 GB RAM,1.3 GHz,5768
5786,887490,Burden of Command™,game,"Apr 8, 2025","Indie,RPG,Strategy",Green Tree Games LLC,Green Tree Games LLC,NaN,24.99$,https://shared.akamai.steamstatic.com/store_it...,"Tactical RPG,Strategy RPG,World War II,Histori...",8,397,80,Windows 10+,1 GB RAM,2 GHz,5787
6244,1286760,Outer Wilds - Original Soundtrack,music,"Jun 18, 2020",NaN,Mobius Digital,Annapurna Interactive,NaN,3.99$,https://shared.akamai.steamstatic.com/store_it...,Soundtrack,8,99,3,NaN,NaN,NaN,6245
7329,3167970,Starless Abyss,game,"Apr 25, 2025","Indie,Strategy",Konafa Games,No More Robots,NaN,19.99$,https://shared.akamai.steamstatic.com/store_it...,"Strategy,Indie,Lovecraftian,Roguelike Deckbuil...",8,133,16,Windows 7 or later,2 GB RAM,2 GHz,7330
7983,888790,Sabbat of the Witch,game,"Oct 26, 2018","Adventure,Casual,Simulation",YUZUSOFT,NekoNyan Ltd.,NaN,29.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Anime,Hentai,Casual,Cute,Adventur...",9,590,25,Windows XP or newer,512 MB RAM,1.3 GHz,7984
8435,1456880,ElecHead,game,"Oct 14, 2021","Action,Adventure,Indie","NamaTakahashi,Tsuyomi",NamaTakahashi,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,"Puzzle Platformer,Puzzle,Platformer,Linear,Pix...",9,654,17,Windows 7+,2 GB RAM,Intel i5+,8436
9170,1202540,Marco & The Galaxy Dragon,game,"Feb 28, 2020","Adventure,Casual,Simulation",TOKYOTOON,Shiravune,NaN,19.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Anime,Female Protagonist,Adventur...",8,436,26,Windows 8/8.1/10,2 GB RAM,2GHz or higher,9171
11028,2482190,Power Fantasy,game,"Dec 4, 2025","Action,RPG,Free To Play",Lava Lamb Games,Lava Lamb Games,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Action,RPG,Bullet Hell,Action Roguelike,Twin S...",0,0,0,Windows 7,1 GB RAM,Dual Core+,11029
11115,1010600,"The Princess, the Stray Cat, and Matters of th...",game,"Jun 17, 2019","Adventure,Casual",TOKYOTOON,"TOKYOTOON,Fruitbat Factory",NaN,6.99$,https://shared.akamai.steamstatic.com/store_it...,"Fantasy,Comedy,Magic,Anime,Romance,Visual Nove...",6,62,16,Windows 7/8/8.1/10,512 MB RAM,1.3GHz and above,11116
11304,2253720,Sim Companies,game,"Aug 31, 2023","Massively Multiplayer,Simulation,Strategy,Free...",Sim Companies s.r.o.,Sim Companies s.r.o.,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Economy,Capitalism,Simulation,Competitive,Mana...",0,0,0,"Windows 7, 8, 10",512 MB RAM,Intel x64,11305
12143,1128260,"The Princess, the Stray Cat, and Matters of th...",game,"Nov 8, 2019","Adventure,Casual",TOKYOTOON,"TOKYOTOON,Fruitbat Factory",NaN,5.99$,https://shared.akamai.steamstatic.com/store_it...,"Fantasy,Magic,Comedy,Romance,Anime,Dating Sim,...",7,25,2,Windows 7/8/8.1/10,512 MB RAM,1.3GHz and above,12144
12447,3521490,Mystery of the Malign,game,"Sep 22, 2025","Adventure,Indie",Gameplay Supremacy,Gameplay Supremacy,NaN,13.99$,https://shared.akamai.steamstatic.com/store_it...,"Mystery,Puzzle,Story Rich,Atmospheric,Explorat...",8,62,5,Windows 7 or better,4 GB RAM,2 GHz Intel i5 or better,12448
13207,780340,Steel Division: Normandy 44 - Back to Hell,dlc,"Feb 13, 2018","Action,Simulation,Strategy",Eugen Systems,Eugen Systems,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,"Strategy,Action,Simulation",7,36,6,64-bit Windows 10 / 8.1 / 7 with Service Pack 1,3 GB RAM,Intel Core i3-2100 (3.1 GHz) or equivalent,13208
14687,1009450,Sankaku Renai: Love Triangle Trouble,game,"May 31, 2019","Adventure,Casual,Simulation",ASa Project,NekoNyan Ltd.,NaN,29.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Anime,Casual,Adventure,Simulation...",8,167,9,Windows XP or newer,512 MB RAM,1.3 GHz,14688
17331,251230,Livelock,game,"Aug 30, 2016","Action,Adventure,Indie",Tuque Games,Arc Games,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,"Action,Top-Down Shooter,Co-op,Indie,Adventure,...",6,241,71,"Windows Vista 64bit, Window 7 64bit, Windows 8...",4 GB RAM,AMD/INTEL Dual-Core 2.4 GHz,17332
17744,1409200,HYPERVIOLENT,game,"Sep 23, 2025","Action,Indie","nfoPRINCE,Terminist Arcade",Fulqrum Publishing,NaN,14.99$,https://shared.akamai.steamstatic.com/store_it...,"Lovecraftian,FPS,Boomer Shooter,Immersive Sim,...",5,78,34,Windows 10,8 GB RAM,Intel i5-7400,17745
17844,2946390,Jump the Track,game,"May 28, 2025","Adventure,Indie",Seed by Seed,Seed by Seed,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,"Story Rich,Comedy,Arcade,Choices Matter,Advent...",7,39,2,Windows 10 x64,8 GB RAM,"Intel Pentium G3250 (2 * 3200), AMD Phenom II ...",17845
18105,1009460,"Hello, Goodbye",game,"Apr 18, 2019","Casual,Simulation",Lump of Sugar,NekoNyan Ltd.,NaN,29.99$,https://shared.akamai.steamstatic.com/store_it...,"Simulation,Casual,Visual Novel,Romance,Anime,S...",7,35,2,Windows XP or newer,512 MB RAM,1.3 GHz,18106
18170,629930,What Remains of Edith Finch - Original Soundtrack,music,"Apr 26, 2017","Adventure,Indie",Giant Sparrow,Annapurna Interactive,NaN,2.49$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Indie,Soundtrack",6,7,3,NaN,85 MB RAM,NaN,18171
21403,931370,Donut County - Original Soundtrack,music,"Aug 28, 2018","Adventure,Casual,Indie",Ben Esposito,Annapurna Interactive,NaN,1.99$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Indie,Casual,Soundtrack",7,13,1,Windows XP SP2,NaN,NaN,21404
21447,359930,The Evil Within: The Executioner,dlc,"May 25, 2015",Action,Tango Gameworks,Bethesda Softworks,NaN,2.99$,https://shared.akamai.steamstatic.com/store_it...,Gore,8,148,26,NaN,NaN,NaN,21448
21887,745160,Gorogoa - Original Soundtrack,music,"Dec 14, 2017","Adventure,Casual,Indie",Buried Signal,Annapurna Interactive,NaN,0.99$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Indie,Casual,Soundtrack",0,7,0,Windows XP SP2,NaN,NaN,21888
24023,1859270,Perfect Partner,game,"Jun 29, 2023","Action,Casual,Indie,Massively Multiplayer,Raci...",RD Studio,RD Studio,NaN,8.99$,https://shared.akamai.steamstatic.com/store_it...,"PvP,Local Co-Op,Team-Based,Online Co-Op,Multip...",0,4,1,Windows 10,8192 MB RAM,Intel Core i5 or AMD equivalent,24024
25223,503270,TOXIKK - [UPGRADE] - Free Edition to FULL GAME,dlc,"Sep 12, 2016","Action,Indie",Reakktor Studios,Schwiezer System GmbH,NaN,14.99$,https://shared.akamai.steamstatic.com/store_it...,"Indie,Action",7,32,3,NaN,NaN,NaN,25224
25303,1644280,The Jewel of Monostructure,game,"Nov 17, 2021","Adventure,Indie",Ignis Sanat,Ignis Sanat 🔥,NaN,5.99$,https://shared.akamai.steamstatic.com/store_it...,"Visual Novel,Dark Fantasy,Story Rich,Atmospher...",7,21,1,Windows 7,1 GB RAM,1.66 Ghz,25304
27302,2570270,Goodbye Volcano High Soundtrack,music,"Aug 29, 2023",NaN,"KO_OP,Dabu,Brigitte Naggar",KO_OP,NaN,9.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,0,8,0,NaN,NaN,NaN,27303
27353,755670,Sleep Tight,game,"Jul 26, 2018","Action,Indie,Strategy",We Are Fuzzy,We Are Fuzzy,NaN,4.99$,https://shared.akamai.steamstatic.com/store_it...,"Indie,Action,Strategy,Shooter,Tower Defense",7,19,3,Windows 10,8 GB RAM,"AMD FX-4350, 4.2 GHz / Intel Core i5-2300, 2.8...",27354
27878,1206330,Florence - Original Soundtrack,music,"Feb 13, 2020",Indie,Mountains,Annapurna Interactive,NaN,0.99$,https://shared.akamai.steamstatic.com/store_it...,"Indie,Soundtrack",7,32,2,NaN,NaN,NaN,27879
28371,919330,Ghost in the pool,game,"Jan 27, 2021","Adventure,Indie",CASCHA GAMES,CASCHA GAMES,NaN,3.99$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Visual Novel,Interactive Fiction,2D,...",7,40,5,Microsoft Window 10,1 GB RAM,Core2Duo 2.4Ghz,28372
28887,2677020,DAVE THE DIVER - DREDGE Content Pack,dlc,"Dec 15, 2023","Adventure,Casual,RPG,Simulation",MINTROCKET,MINTROCKET,NaN,0$,https://shared.akamai.steamstatic.com/store_it...,"Casual,Adventure,RPG,Simulation,Pixel Graphics...",0,0,0,Windows 7 64 bit,8 GB RAM,Intel Core i3 Dual Core,28888
28982,1147970,Abode 2,game,"Nov 7, 2019",Adventure,Overflow,Overflow,NaN,14.99$,https://shared.akamai.steamstatic.com/store_it...,"Adventure,Puzzle,Sci-fi,Atmospheric,VR,Escape ...",8,79,17,"Windows 7 SP1, Windows 8.1 or Windows 10",8 GB RAM,"Intel® i5-4590, AMD FX 8350 equivalent or better",28983

In [35]:
# Nhận thấy có khá nhiều game không có phần mô tả, tuy nhiên ta vẫn có thể sử dụng thông tin khác để khuyến nghị game nên ta sẽ fillna "No description" cho những game này
df['Description'] = df['Description'].fillna("No description")

In [36]:
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate             0
Genres                406
Developers              0
Publishers              0
Description             0
price                   0
Thumbnail               0
Tags                 1603
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement        2923
MemoryRequirement    3970
CpuRequirement       3844
Rank                    0
dtype: int64

In [37]:
# Với những thuộc tính yêu cầu về os, memory, cpu nếu NULL thì ta có thể coi nó là không có yêu cầu nên ta fillna bằng "No requirement" 
df['OsRequirement'] = df['OsRequirement'].fillna("No requirement")
df['MemoryRequirement'] = df['MemoryRequirement'].fillna("No requirement")  
df['CpuRequirement'] = df['CpuRequirement'].fillna("No requirement")

In [38]:
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate             0
Genres                406
Developers              0
Publishers              0
Description             0
price                   0
Thumbnail               0
Tags                 1603
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement           0
MemoryRequirement       0
CpuRequirement          0
Rank                    0
dtype: int64

In [39]:
# Dựa vào dữ liệu ta có thể thấy rằng tags là 1 cách thể hiện rõ ràng hơn của genres, vậy với những tags NULL ta có thể thay bằng cách sử dụng genres, và drop cột genres bởi đã có feature tags thể hiện rõ hơn 
df["Tags"] = df['Tags'].fillna(df['Genres'])    
df.drop(columns=['Genres'], inplace=True)

In [40]:
df.isnull().sum()

Appid                  0
Name                   0
Type                   0
ReleaseDate            0
Developers             0
Publishers             0
Description            0
price                  0
Thumbnail              0
Tags                 229
ReviewScore            0
PositiveReview         0
NegativeReview         0
OsRequirement          0
MemoryRequirement      0
CpuRequirement         0
Rank                   0
dtype: int64

In [41]:
display(df[df['Tags'].isnull() & df['Description'] == "No description"])

Empty DataFrame
Columns: [Appid, Name, Type, ReleaseDate, Developers, Publishers, Description, price, Thumbnail, Tags, ReviewScore, PositiveReview, NegativeReview, OsRequirement, MemoryRequirement, CpuRequirement, Rank]
Index: []

In [42]:
# ta thấy không tồn tại game nào vừa không có tags và vừa không có description, vậy nếu ta điền tags bằng 'No tags' xong ta sẽ khuyến nghị dựa trên nội dung
df['Tags'] = df['Tags'].fillna("No tags")

In [43]:
df.isnull().sum()

Appid                0
Name                 0
Type                 0
ReleaseDate          0
Developers           0
Publishers           0
Description          0
price                0
Thumbnail            0
Tags                 0
ReviewScore          0
PositiveReview       0
NegativeReview       0
OsRequirement        0
MemoryRequirement    0
CpuRequirement       0
Rank                 0
dtype: int64

In [45]:
df.to_csv('data.csv', index=False)