# Tải thư viện cần thiết

In [1]:
!pip install gdown

Requirement already satisfied: gdown in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.0.0)
Requirement already satisfied: beautifulsoup4 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gdown) (4.13.3)
Requirement already satisfied: filelock in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4->gdown) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests[socks]->gdown) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests[socks]->gdown) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests[socks]->gdown) (2025.1.31)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in C:\Users\nguye\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->gdown) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Import thư viện

In [2]:
import pandas as pd 
import numpy as np 
import gdown

# Tải dữ liệu

In [3]:
!gdown --folder https://drive.google.com/drive/folders/1n8-rufdSRkmGijK44KbriPOpRhy-1vWY

Processing file 1a3Q60DixKdM4RpgpytPOUaImZlWuMlYD delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv
Processing file 1lVPrcxZPnEuQSPRX91pTDyQyTgTHc025 delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv
Processing file 1RBCBg8NXOESuGKHgG7CSLpPRoqibUoHm not_delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv
Processing file 1w7sCPMKrWvF_MsZa1X3o3G3pyBz5CS9C not_delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv

Retrieving folder contents
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1a3Q60DixKdM4RpgpytPOUaImZlWuMlYD
To: c:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv

  0%|          | 0.00/2.09M [00:00<?, ?B/s]
 25%|██▌       | 524k/2.09M [00:00<00:01, 1.45MB/s]
 50%|█████     | 1.05M/2.09M [00:00<00:00, 2.48MB/s]
 75%|███████▌  | 1.57M/2.09M [00:00<00:00, 3.21MB/s]
100%|██████████| 2.09M/2.09M [00:00<00:00, 3.53MB/s]
Downloading...
From: https://drive.google.com/uc?id=1lVPrcxZPnEuQSPRX91pTDyQyTgTHc025
To: c:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv

  0%|          | 0.00/4.62M [00:00<?, ?B/s]
 11%|█▏        | 524k/4.62M [00:00<00:03, 1.13MB/s]
 34%|███▍      | 1.57M/4.62M [00:00<00:01, 3.03MB/s]
 57%|█████▋    | 2.62M/4.62M [00:00<00:00, 3.85MB/s]
 68%|██████▊   | 3.15M/4.62M [00:00<00:00, 4.06MB/s]
 91%|█████████ | 4.19M/4.62M [00:01<00:00, 4.65MB/s]
100%|██████████| 4.62M/4.62M [00:01<00:00, 4.13MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RBCBg8NXOESuGKHgG7CSLpPRoqibUoHm
To: c:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\not_delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv

  0%|          | 0.00/83.4M [00:00<?, ?B/s]
  1%|          | 524k/83.4M [00:00<01:08, 1.20MB/s]
  2%|▏         | 1.57M/83.4M [00:00<00:26, 3.13MB/s]
  4%|▍         | 3.15M/83.4M [00:00<00:19, 4.04MB/s]
  5%|▌         | 4.19M/83.4M [00:01<00:15, 5.05MB/s]
  7%|▋         | 5.77M/83.4M [00:01<00:12, 6.15MB/s]
  9%|▉         | 7.34M/83.4M [00:01<00:10, 7.11MB/s]
 10%|█         | 8.39M/83.4M [00:01<00:10, 7.26MB/s]
 11%|█▏        | 9.44M/83.4M [00:01<00:10, 7.38MB/s]
 13%|█▎        | 10.5M/83.4M [00:01<00:09, 7.49MB/s]
 14%|█▍        | 11.5M/83.4M [00:02<00:11, 6.41MB/s]
 16%|█▌        | 13.1M/83.4M [00:02<00:08, 7.90MB/s]
 17%|█▋        | 14.2M/83.4M [00:02<00:09, 7.55MB/s]
 18%|█▊        | 15.2M/83.4M [00:02<00:10, 6.44MB/s]
 20%|██        | 16.8M/83.4M [00:02<00:08, 7.82MB/s]
 21%|██▏       | 17.8M/83.4M [00:02<00:08, 7.72MB/s]
 23%|██▎       | 18.9M/83.4M [00:02<00:08, 7.63MB/s]
 24%|██▍       | 19.9M/83.4M [00:03<00:08, 7.57MB/s]
 25%|██▌       | 21.0M/83.4M [00:03<00:10, 6.04MB/s]
 26%|██▋       | 22.0M/83.4M [00:03<00:09, 6.55MB/s]
 28%|██▊       | 23.1M/83.4M [00:03<00:08, 6.70MB/s]
 29%|██▉       | 24.1M/83.4M [00:03<00:08, 6.78MB/s]
 30%|███       | 25.2M/83.4M [00:03<00:08, 6.70MB/s]
 31%|███▏      | 26.2M/83.4M [00:04<00:08, 6.76MB/s]
 33%|███▎      | 27.3M/83.4M [00:04<00:08, 6.59MB/s]
 34%|███▍      | 28.3M/83.4M [00:04<00:08, 6.46MB/s]
 35%|███▌      | 29.4M/83.4M [00:04<00:08, 6.54MB/s]
 36%|███▋      | 30.4M/83.4M [00:04<00:08, 6.59MB/s]
 38%|███▊      | 31.5M/83.4M [00:04<00:08, 5.90MB/s]
 39%|███▉      | 32.5M/83.4M [00:05<00:07, 6.70MB/s]
 40%|████      | 33.6M/83.4M [00:05<00:07, 6.68MB/s]
 41%|████▏     | 34.6M/83.4M [00:05<00:07, 6.60MB/s]
 43%|████▎     | 35.7M/83.4M [00:05<00:07, 6.60MB/s]
 44%|████▍     | 36.7M/83.4M [00:05<00:07, 5.96MB/s]
 45%|████▌     | 37.7M/83.4M [00:05<00:07, 5.78MB/s]
 47%|████▋     | 39.3M/83.4M [00:06<00:05, 7.35MB/s]
 48%|████▊     | 40.4M/83.4M [00:06<00:05, 7.53MB/s]
 50%|████▉     | 41.4M/83.4M [00:06<00:05, 7.14MB/s]
 51%|█████     | 42.5M/83.4M [00:06<00:05, 7.72MB/s]
 52%|█████▏    | 43.5M/83.4M [00:06<00:04, 8.25MB/s]
 53%|█████▎    | 44.6M/83.4M [00:06<00:05, 7.22MB/s]
 55%|█████▌    | 46.1M/83.4M [00:06<00:04, 8.07MB/s]
 57%|█████▋    | 47.2M/83.4M [00:07<00:04, 7.95MB/s]
 58%|█████▊    | 48.2M/83.4M [00:07<00:05, 6.73MB/s]
 59%|█████▉    | 49.3M/83.4M [00:07<00:05, 6.57MB/s]
 61%|██████    | 50.9M/83.4M [00:07<00:04, 7.48MB/s]
 62%|██████▏   | 51.9M/83.4M [00:07<00:04, 7.59MB/s]
 63%|██████▎   | 53.0M/83.4M [00:07<00:03, 7.62MB/s]
 65%|██████▍   | 54.0M/83.4M [00:08<00:03, 7.60MB/s]
 66%|██████▌   | 55.1M/83.4M [00:08<00:03, 7.36MB/s]
 67%|██████▋   | 56.1M/83.4M [00:08<00:03, 7.45MB/s]
 69%|██████▊   | 57.1M/83.4M [00:08<00:03, 7.48MB/s]
 70%|██████▉   | 58.2M/83.4M [00:08<00:03, 7.47MB/s]
 71%|███████   | 59.2M/83.4M [00:08<00:03, 7.34MB/s]
 72%|███████▏  | 60.3M/83.4M [00:08<00:03, 7.21MB/s]
 74%|███████▎  | 61.3M/83.4M [00:08<00:02, 7.51MB/s]
 75%|███████▍  | 62.4M/83.4M [00:09<00:02, 7.88MB/s]
 76%|███████▌  | 63.4M/83.4M [00:09<00:02, 8.21MB/s]
 77%|███████▋  | 64.5M/83.4M [00:09<00:03, 6.19MB/s]
 80%|███████▉  | 66.6M/83.4M [00:09<00:02, 8.36MB/s]
 81%|████████  | 67.6M/83.4M [00:09<00:01, 8.03MB/s]
 82%|████████▏ | 68.7M/83.4M [00:09<00:01, 7.82MB/s]
 84%|████████▎ | 69.7M/83.4M [00:10<00:01, 7.71MB/s]
 85%|████████▍ | 70.8M/83.4M [00:10<00:01, 7.62MB/s]
 86%|████████▌ | 71.8M/83.4M [00:10<00:01, 7.65MB/s]
 87%|████████▋ | 72.9M/83.4M [00:10<00:01, 5.96MB/s]
 89%|████████▊ | 73.9M/83.4M [00:10<00:01, 6.51MB/s]
 90%|████████▉ | 75.0M/83.4M [00:10<00:01, 6.65MB/s]
 91%|█████████ | 76.0M/83.4M [00:11<00:01, 6.79MB/s]
 92%|█████████▏| 77.1M/83.4M [00:11<00:00, 6.75MB/s]
 94%|█████████▎| 78.1M/83.4M [00:11<00:00, 7.00MB/s]
 95%|█████████▍| 79.2M/83.4M [00:11<00:00, 7.18MB/s]
 96%|█████████▌| 80.2M/83.4M [00:11<00:00, 7.50MB/s]
 97%|█████████▋| 81.3M/83.4M [00:11<00:00, 6.91MB/s]
 99%|█████████▉| 82.8M/83.4M [00:12<00:00, 6.63MB/s]
100%|██████████| 83.4M/83.4M [00:12<00:00, 6.93MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1w7sCPMKrWvF_MsZa1X3o3G3pyBz5CS9C
From (redirected): https://drive.google.com/uc?id=1w7sCPMKrWvF_MsZa1X3o3G3pyBz5CS9C&confirm=t&uuid=166440be-28ea-4b42-81b0-0564e1783487
To: c:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\not_delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv

  0%|          | 0.00/181M [00:00<?, ?B/s]
  0%|          | 524k/181M [00:00<02:07, 1.42MB/s]
  1%|          | 1.57M/181M [00:00<00:49, 3.61MB/s]
  2%|▏         | 3.15M/181M [00:00<00:39, 4.50MB/s]
  2%|▏         | 4.19M/181M [00:00<00:31, 5.62MB/s]
  3%|▎         | 5.24M/181M [00:01<00:27, 6.43MB/s]
  3%|▎         | 6.29M/181M [00:01<00:25, 7.00MB/s]
  4%|▍         | 7.34M/181M [00:01<00:23, 7.38MB/s]
  5%|▍         | 8.39M/181M [00:01<00:26, 6.54MB/s]
  5%|▌         | 9.44M/181M [00:01<00:23, 7.40MB/s]
  6%|▌         | 10.5M/181M [00:01<00:22, 7.45MB/s]
  6%|▋         | 11.5M/181M [00:01<00:24, 6.88MB/s]
  7%|▋         | 12.6M/181M [00:02<00:22, 7.50MB/s]
  8%|▊         | 13.6M/181M [00:02<00:21, 7.78MB/s]
  8%|▊         | 14.7M/181M [00:02<00:21, 7.61MB/s]
  9%|▊         | 15.7M/181M [00:02<00:22, 7.42MB/s]
  9%|▉         | 16.8M/181M [00:02<00:22, 7.18MB/s]
 10%|▉         | 17.8M/181M [00:02<00:23, 7.00MB/s]
 10%|█         | 18.9M/181M [00:02<00:22, 7.13MB/s]
 11%|█         | 19.9M/181M [00:03<00:22, 7.14MB/s]
 12%|█▏        | 21.0M/181M [00:03<00:22, 7.20MB/s]
 12%|█▏        | 22.0M/181M [00:03<00:22, 7.13MB/s]
 13%|█▎        | 23.1M/181M [00:03<00:22, 7.13MB/s]
 13%|█▎        | 24.1M/181M [00:03<00:21, 7.25MB/s]
 14%|█▍        | 25.2M/181M [00:03<00:20, 7.70MB/s]
 14%|█▍        | 26.2M/181M [00:03<00:24, 6.29MB/s]
 15%|█▌        | 27.8M/181M [00:04<00:20, 7.55MB/s]
 16%|█▌        | 29.4M/181M [00:04<00:22, 6.78MB/s]
 17%|█▋        | 30.4M/181M [00:04<00:20, 7.27MB/s]
 17%|█▋        | 31.5M/181M [00:04<00:22, 6.79MB/s]
 18%|█▊        | 32.5M/181M [00:04<00:23, 6.47MB/s]
 18%|█▊        | 33.6M/181M [00:05<00:23, 6.17MB/s]
 19%|█▉        | 34.6M/181M [00:05<00:23, 6.12MB/s]
 20%|█▉        | 35.7M/181M [00:05<00:23, 6.10MB/s]
 20%|██        | 36.7M/181M [00:05<00:23, 6.08MB/s]
 21%|██        | 37.7M/181M [00:05<00:24, 5.93MB/s]
 21%|██▏       | 38.8M/181M [00:05<00:24, 5.82MB/s]
 22%|██▏       | 39.8M/181M [00:06<00:26, 5.32MB/s]
 23%|██▎       | 40.9M/181M [00:06<00:26, 5.39MB/s]
 23%|██▎       | 41.9M/181M [00:06<00:25, 5.50MB/s]
 24%|██▎       | 43.0M/181M [00:06<00:23, 5.80MB/s]
 25%|██▍       | 44.6M/181M [00:06<00:19, 6.94MB/s]
 25%|██▌       | 45.6M/181M [00:07<00:22, 6.01MB/s]
 26%|██▌       | 47.2M/181M [00:07<00:18, 7.33MB/s]
 27%|██▋       | 48.2M/181M [00:07<00:21, 6.27MB/s]
 27%|██▋       | 49.3M/181M [00:07<00:22, 5.92MB/s]
 28%|██▊       | 50.3M/181M [00:07<00:19, 6.59MB/s]
 29%|██▊       | 51.9M/181M [00:07<00:17, 7.56MB/s]
 29%|██▉       | 53.0M/181M [00:08<00:20, 6.18MB/s]
 30%|███       | 54.5M/181M [00:08<00:16, 7.54MB/s]
 31%|███       | 55.6M/181M [00:08<00:17, 7.31MB/s]
 31%|███       | 56.6M/181M [00:08<00:16, 7.43MB/s]
 32%|███▏      | 57.7M/181M [00:08<00:17, 7.27MB/s]
 32%|███▏      | 58.7M/181M [00:08<00:18, 6.48MB/s]
 33%|███▎      | 59.8M/181M [00:09<00:17, 6.95MB/s]
 34%|███▎      | 60.8M/181M [00:09<00:17, 6.99MB/s]
 34%|███▍      | 61.9M/181M [00:09<00:17, 7.00MB/s]
 35%|███▍      | 62.9M/181M [00:09<00:16, 6.98MB/s]
 35%|███▌      | 64.0M/181M [00:09<00:16, 7.08MB/s]
 36%|███▌      | 65.0M/181M [00:09<00:16, 7.12MB/s]
 36%|███▋      | 66.1M/181M [00:09<00:14, 7.73MB/s]
 37%|███▋      | 67.1M/181M [00:10<00:19, 6.01MB/s]
 38%|███▊      | 68.7M/181M [00:10<00:14, 7.82MB/s]
 38%|███▊      | 69.7M/181M [00:10<00:14, 7.80MB/s]
 39%|███▉      | 70.8M/181M [00:10<00:14, 7.49MB/s]
 40%|███▉      | 71.8M/181M [00:10<00:14, 7.53MB/s]
 40%|████      | 72.9M/181M [00:10<00:14, 7.64MB/s]
 41%|████      | 73.9M/181M [00:11<00:15, 7.01MB/s]
 41%|████▏     | 75.0M/181M [00:11<00:14, 7.60MB/s]
 42%|████▏     | 76.0M/181M [00:11<00:13, 7.79MB/s]
 42%|████▏     | 77.1M/181M [00:11<00:13, 7.62MB/s]
 43%|████▎     | 78.1M/181M [00:11<00:13, 7.53MB/s]
 44%|████▎     | 79.2M/181M [00:11<00:13, 7.64MB/s]
 44%|████▍     | 80.2M/181M [00:11<00:13, 7.68MB/s]
 45%|████▍     | 81.3M/181M [00:11<00:12, 7.73MB/s]
 45%|████▌     | 82.3M/181M [00:12<00:12, 7.77MB/s]
 46%|████▌     | 83.4M/181M [00:12<00:12, 7.72MB/s]
 47%|████▋     | 84.4M/181M [00:12<00:14, 6.56MB/s]
 47%|████▋     | 86.0M/181M [00:12<00:12, 7.69MB/s]
 48%|████▊     | 87.0M/181M [00:12<00:12, 7.65MB/s]
 49%|████▊     | 88.1M/181M [00:12<00:12, 7.72MB/s]
 49%|████▉     | 89.1M/181M [00:13<00:13, 6.92MB/s]
 50%|████▉     | 90.2M/181M [00:13<00:14, 6.36MB/s]
 50%|█████     | 91.2M/181M [00:13<00:12, 7.03MB/s]
 51%|█████     | 92.3M/181M [00:13<00:11, 7.53MB/s]
 51%|█████▏    | 93.3M/181M [00:13<00:11, 7.81MB/s]
 52%|█████▏    | 94.4M/181M [00:13<00:12, 6.98MB/s]
 53%|█████▎    | 95.4M/181M [00:14<00:13, 6.26MB/s]
 54%|█████▍    | 97.5M/181M [00:14<00:10, 8.24MB/s]
 54%|█████▍    | 98.6M/181M [00:14<00:11, 7.24MB/s]
 55%|█████▍    | 99.6M/181M [00:14<00:11, 7.36MB/s]
 55%|█████▌    | 101M/181M [00:14<00:12, 6.60MB/s]
 56%|█████▌    | 102M/181M [00:14<00:11, 6.82MB/s]
 57%|█████▋    | 103M/181M [00:15<00:11, 6.78MB/s]
 57%|█████▋    | 104M/181M [00:15<00:11, 6.95MB/s]
 58%|█████▊    | 105M/181M [00:15<00:10, 7.04MB/s]
 58%|█████▊    | 106M/181M [00:15<00:10, 6.98MB/s]
 59%|█████▉    | 107M/181M [00:15<00:11, 6.25MB/s]
 60%|█████▉    | 108M/181M [00:15<00:10, 6.81MB/s]
 60%|██████    | 109M/181M [00:15<00:11, 6.24MB/s]
 61%|██████    | 110M/181M [00:16<00:10, 7.01MB/s]
 62%|██████▏   | 112M/181M [00:16<00:08, 8.06MB/s]
 62%|██████▏   | 113M/181M [00:16<00:09, 7.63MB/s]
 63%|██████▎   | 114M/181M [00:16<00:08, 7.79MB/s]
 63%|██████▎   | 115M/181M [00:16<00:09, 6.89MB/s]
 64%|██████▍   | 116M/181M [00:16<00:08, 7.30MB/s]
 64%|██████▍   | 117M/181M [00:17<00:09, 6.94MB/s]
 65%|██████▌   | 118M/181M [00:17<00:09, 6.44MB/s]
 66%|██████▌   | 119M/181M [00:17<00:09, 6.25MB/s]
 66%|██████▌   | 120M/181M [00:17<00:11, 5.43MB/s]
 67%|██████▋   | 121M/181M [00:17<00:10, 5.60MB/s]
 67%|██████▋   | 122M/181M [00:17<00:10, 5.66MB/s]
 68%|██████▊   | 123M/181M [00:18<00:10, 5.75MB/s]
 68%|██████▊   | 124M/181M [00:18<00:09, 5.90MB/s]
 69%|██████▉   | 125M/181M [00:18<00:09, 5.76MB/s]
 70%|██████▉   | 126M/181M [00:18<00:08, 6.12MB/s]
 70%|███████   | 127M/181M [00:18<00:07, 6.91MB/s]
 71%|███████   | 128M/181M [00:18<00:07, 7.14MB/s]
 72%|███████▏  | 130M/181M [00:19<00:08, 6.28MB/s]
 73%|███████▎  | 132M/181M [00:19<00:06, 7.71MB/s]
 73%|███████▎  | 133M/181M [00:19<00:06, 7.76MB/s]
 74%|███████▎  | 134M/181M [00:19<00:06, 7.64MB/s]
 74%|███████▍  | 135M/181M [00:19<00:06, 7.58MB/s]
 75%|███████▍  | 136M/181M [00:19<00:06, 7.35MB/s]
 75%|███████▌  | 137M/181M [00:20<00:05, 7.62MB/s]
 76%|███████▌  | 138M/181M [00:20<00:05, 7.69MB/s]
 77%|███████▋  | 139M/181M [00:20<00:05, 7.53MB/s]
 77%|███████▋  | 140M/181M [00:20<00:05, 7.48MB/s]
 78%|███████▊  | 141M/181M [00:20<00:05, 7.29MB/s]
 78%|███████▊  | 142M/181M [00:20<00:05, 7.01MB/s]
 79%|███████▉  | 143M/181M [00:20<00:05, 7.23MB/s]
 79%|███████▉  | 144M/181M [00:21<00:05, 7.02MB/s]
 80%|████████  | 145M/181M [00:21<00:05, 6.21MB/s]
 81%|████████  | 146M/181M [00:21<00:05, 6.67MB/s]
 81%|████████  | 147M/181M [00:21<00:04, 7.20MB/s]
 82%|████████▏ | 148M/181M [00:21<00:04, 7.69MB/s]
 82%|████████▏ | 149M/181M [00:21<00:03, 8.10MB/s]
 83%|████████▎ | 150M/181M [00:21<00:04, 6.55MB/s]
 84%|████████▍ | 152M/181M [00:22<00:03, 8.10MB/s]
 84%|████████▍ | 153M/181M [00:22<00:03, 8.19MB/s]
 85%|████████▍ | 154M/181M [00:22<00:03, 7.79MB/s]
 86%|████████▌ | 155M/181M [00:22<00:03, 6.99MB/s]
 86%|████████▌ | 156M/181M [00:22<00:03, 7.06MB/s]
 87%|████████▋ | 157M/181M [00:22<00:03, 7.08MB/s]
 87%|████████▋ | 158M/181M [00:23<00:04, 5.56MB/s]
 88%|████████▊ | 159M/181M [00:23<00:03, 6.11MB/s]
 88%|████████▊ | 160M/181M [00:23<00:03, 6.73MB/s]
 89%|████████▉ | 161M/181M [00:23<00:02, 7.08MB/s]
 90%|████████▉ | 163M/181M [00:23<00:02, 6.67MB/s]
 90%|█████████ | 164M/181M [00:23<00:02, 6.99MB/s]
 91%|█████████ | 165M/181M [00:23<00:02, 7.23MB/s]
 91%|█████████▏| 166M/181M [00:24<00:02, 7.47MB/s]
 92%|█████████▏| 167M/181M [00:24<00:01, 7.72MB/s]
 92%|█████████▏| 168M/181M [00:24<00:01, 7.33MB/s]
 93%|█████████▎| 169M/181M [00:24<00:01, 7.83MB/s]
 94%|█████████▎| 170M/181M [00:24<00:01, 7.59MB/s]
 94%|█████████▍| 171M/181M [00:24<00:01, 7.63MB/s]
 95%|█████████▍| 172M/181M [00:24<00:01, 8.00MB/s]
 95%|█████████▌| 173M/181M [00:25<00:01, 7.93MB/s]
 96%|█████████▌| 174M/181M [00:25<00:01, 6.75MB/s]
 97%|█████████▋| 176M/181M [00:25<00:00, 7.84MB/s]
 97%|█████████▋| 177M/181M [00:25<00:00, 7.82MB/s]
 98%|█████████▊| 178M/181M [00:25<00:00, 6.87MB/s]
 99%|█████████▊| 179M/181M [00:25<00:00, 7.06MB/s]
 99%|█████████▉| 180M/181M [00:26<00:00, 7.16MB/s]
100%|█████████▉| 181M/181M [00:26<00:00, 6.48MB/s]
100%|██████████| 181M/181M [00:26<00:00, 6.92MB/s]
Download completed

In [4]:
delay_4_6 = pd.read_csv(r"C:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv")
not_delay_4_6 = pd.read_csv(r"C:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\not_delay_4_6_CONDITION_PRODUCT_SUPPLIER.csv", dtype={10: str, 42: str})
delay_7_9 = pd.read_csv(r"C:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv")
not_delay_7_9 = pd.read_csv(r"C:\Users\nguye\SteamCrawler\Bài Tập thực Hành\Lab 3\Data for practice\not_delay_7_9_CONDITION_PRODUCT_SUPPLIER.csv", dtype={34: str})

# Kiểm tra sơ bộ về dataset

In [5]:
datasets = {
    "delay_4_6": delay_4_6,
    "not_delay_4_6": not_delay_4_6,
    "delay_7_9": delay_7_9,
    "not_delay_7_9": not_delay_7_9
}

## Check Shape

In [6]:
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

delay_4_6: (9733, 47)
not_delay_4_6: (389320, 47)
delay_7_9: (26217, 37)
not_delay_7_9: (1048680, 37)

## Xem thử 5 dữ liệu của 5 hàng đầu tiên

In [7]:
for name, df in datasets.items():

    print("=" * 60)
    print(name)
    print("=" * 60)

    display(df.head())

============================================================
delay_4_6
============================================================

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,IO_UNFIT_FLG,WEIGHT_UNIT,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME,SUPPLIER_CATEGORY_CD,PRODUCT_ASSORT
0,2022-04-04 00:00:00,MJP,1000074430653,21034701,74,HAK1,F7371210001,8107,1,1,...,4,1,0,g,401,805169,NaN,120324,5,
1,2022-04-26 00:00:00,MJP,5004180038393,23028764,4180,S3M1,K9045010089,8484,1,1,...,26,2,0,g,455,NaN,NaN,171618,5,
2,2022-04-19 00:00:00,MJP,1000074434232,21059031,74,THT1,F5109250104,8233,1,1,...,19,2,0,g,451,864727,NaN,184619,5,
3,2022-04-22 00:00:00,MJP,1000074434911,3731227,74,MSM1,79014275005,3013,1,1,...,22,5,0,g,410,NaN,NaN,93246,5,
4,2022-04-22 00:00:00,MJP,1000074435036,3954111,74,MSM1,30357450001,3081,1,1,...,22,5,0,g,410,NaN,NaN,153401,5,

============================================================
not_delay_4_6
============================================================

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,IO_UNFIT_FLG,WEIGHT_UNIT,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME,SUPPLIER_CATEGORY_CD,PRODUCT_ASSORT
0,2022-04-27 00:00:00,MJP,1082054645443,3632511,82054,MSM1,30396270007,3764,1,1,...,27,3,0,g,,NaN,NaN,155111,3,
1,2022-05-09 00:00:00,MJP,7520721962065,3722111,520721,MSM1,30263990002,0143,91,1,...,9,1,0,g,,NaN,NaN,155051,5,
2,2022-05-24 00:00:00,MJP,5124924002323,3643111,124924,MSM1,30160450001,3764,13,1,...,24,2,0,g,,NaN,NaN,174708,3,
3,2022-06-09 00:00:00,MJP,1000450115481,3731228,450,MSM1,79001971001,7021,1,1,...,9,4,0,g,,NaN,NaN,150807,5,
4,2022-04-15 00:00:00,MJP,7131060937169,3954109,131060,MSM1,30350800028,3186,1,1,...,15,5,0,g,,NaN,NaN,95047,5,

============================================================
delay_7_9
============================================================

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,PACK QTY,WEIGHT PER PIECE,SUPPLIER_DIV,SPECIAL_DIV,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME
0,2022-08-25,MJP,08344472000137,21031103,344472,OSA1,F7171260007,8121,8,1,...,0,1020,2.0,0,25,4,453.0,NaN,NaN,135557
1,2022-08-12,MJP,06000641365551,3712333,641,MSM1,30071630003,0263,1,1,...,0,120,1.0,0,12,5,451.0,NaN,NaN,134532
2,2022-07-08,MJP,07032167936864,21045918,32167,SMC1,F7499483132,9102,1,1,...,0,18000,3.0,0,8,5,410.0,NaN,NaN,160936
3,2022-07-08,MJP,01710046000973,21058302,710046,MIB1,F4524160001,9163,1,1,...,0,500,2.0,0,8,5,453.0,NaN,NaN,160702
4,2022-08-25,MJP,07107539916817,21050569,107539,NIQ1,F3017310155,9176,6,1,...,0,36,2.0,0,25,4,455.0,NaN,NaN,160244

============================================================
not_delay_7_9
============================================================

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,PACK QTY,WEIGHT PER PIECE,SUPPLIER_DIV,SPECIAL_DIV,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME
0,2022-09-21,MJP,HA860555020344,3622716,142741,MSM1,30189700018,0143,4,1,...,0,14,1.0,0,21,3,NaN,NaN,NaN,171936
1,2022-08-09,MJP,CAW057PL006722,2041801,254252,MSM1,23300470001,0214,9,1,...,0,50,1.0,0,9,2,NaN,NaN,NaN,145752
2,2022-08-02,MJP,08105551925469,5010044,105551,MSM1,41340018124,4050,3,1,...,0,289,1.0,0,2,2,NaN,NaN,NaN,170618
3,2022-07-06,MJP,08051197943406,3954111,51197,MSM1,30357280003,3186,2,1,...,0,178,1.0,0,6,3,NaN,NaN,NaN,134348
4,2022-07-26,MJP,08102763906512,3643111,102763,MSM1,30161110001,0143,2,1,...,0,1,1.0,0,26,2,NaN,NaN,NaN,155327

## kiểm tra số lượng non-null và kiểu dữ liệu của từng cột

In [8]:
for name, df in datasets.items():

    print("=" * 60)
    print(name)
    print("=" * 60)

    print(df.info())

============================================================
delay_4_6
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9733 entries, 0 to 9732
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Order date                       9733 non-null   object
 1   SUBSIDIARY_CD                    9733 non-null   object
 2   GLOBAL_NO                        9733 non-null   int64
 3   CLASSIFY_CD                      9733 non-null   int64
 4   CUST_CD                          9733 non-null   int64
 5   BRAND_CD                         9733 non-null   object
 6   INNER_CD                         9733 non-null   object
 7   SUPPLIER_CD                      9733 non-null   object
 8   Sales order line number          9733 non-null   int64
 9   Stock class                      9733 non-null   int64
 10  Consider count hodiday Saturday  9733 non-null   int64
 11  SO QTY                           9733 non-null   int64
 12  OTHER AREA SHIP DIV              9733 non-null   object
 13  ALLOCATION QTY                   9733 non-null   int64
 14  SUPPLIER INV AMOUNT              9733 non-null   float64
 15  PACKING RANK                     9733 non-null   object
 16  PRODUCT_CD                       9733 non-null   object
 17  PRODUCT ATTRIBUTION              9733 non-null   int64
 18  SPECIAL DIV                      9733 non-null   int64
 19  LOGICAL PLANT                    9733 non-null   int64
 20  PURCHASE AMOUNT                  9733 non-null   float64
 21  VSD                              9733 non-null   object
 22  DIRECT SHIP FLG                  9733 non-null   int64
 23  DELI_DIV                         9733 non-null   object
 24  label                            9733 non-null   int64
 25  Ship Mode                        9252 non-null   object
 26  SHIP DECISION NO                 9642 non-null   float64
 27  PACK QTY                         9733 non-null   int64
 28  WEIGHT PER PIECE                 9733 non-null   int64
 29  SUPPLIER_DIV                     9733 non-null   float64
 30  HEAVY_FLG                        9733 non-null   int64
 31  EXPENSIVE_FLG                    9733 non-null   int64
 32  SPECIAL_DIV                      9733 non-null   int64
 33  ACTUAL_SHIP_DAYS                 9733 non-null   int64
 34  SPECIFY_PRODUCTION_DAYS          9733 non-null   int64
 35  SPECIFY_SHIP_DAYS                9733 non-null   int64
 36  HAZARD_FLG                       9733 non-null   int64
 37  SO_DAY_OF_MONTH                  9733 non-null   int64
 38  SO_DAY_OF_WEEK                   9733 non-null   int64
 39  IO_UNFIT_FLG                     9733 non-null   int64
 40  WEIGHT_UNIT                      9643 non-null   object
 41  REASON_CD                        9733 non-null   object
 42  SOUF_RCV_NO                      586 non-null    object
 43  QTUF_RCV_NO                      32 non-null     float64
 44  SO_TIME                          9733 non-null   int64
 45  SUPPLIER_CATEGORY_CD             9733 non-null   int64
 46  PRODUCT_ASSORT                   9733 non-null   object
dtypes: float64(5), int64(27), object(15)
memory usage: 3.5+ MB
None
============================================================
not_delay_4_6
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 389320 entries, 0 to 389319
Data columns (total 47 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Order date                       389320 non-null  object
 1   SUBSIDIARY_CD                    389320 non-null  object
 2   GLOBAL_NO                        389320 non-null  int64
 3   CLASSIFY_CD                      389320 non-null  int64
 4   CUST_CD                          389320 non-null  int64
 5   BRAND_CD                         389320 non-null  object
 6   INNER_CD                         389320 non-null  object
 7   SUPPLIER_CD                      389320 non-null  object
 8   Sales order line number          389320 non-null  int64
 9   Stock class                      389320 non-null  int64
 10  Consider count hodiday Saturday  389320 non-null  object
 11  SO QTY                           389320 non-null  int64
 12  OTHER AREA SHIP DIV              389320 non-null  object
 13  ALLOCATION QTY                   389320 non-null  int64
 14  SUPPLIER INV AMOUNT              389320 non-null  float64
 15  PACKING RANK                     389320 non-null  object
 16  PRODUCT_CD                       389320 non-null  object
 17  PRODUCT ATTRIBUTION              389320 non-null  int64
 18  SPECIAL DIV                      389320 non-null  int64
 19  LOGICAL PLANT                    389320 non-null  int64
 20  PURCHASE AMOUNT                  389320 non-null  float64
 21  VSD                              389320 non-null  object
 22  DIRECT SHIP FLG                  389320 non-null  int64
 23  DELI_DIV                         389320 non-null  object
 24  label                            389320 non-null  int64
 25  Ship Mode                        383213 non-null  object
 26  SHIP DECISION NO                 356094 non-null  float64
 27  PACK QTY                         389320 non-null  int64
 28  WEIGHT PER PIECE                 389320 non-null  int64
 29  SUPPLIER_DIV                     389316 non-null  float64
 30  HEAVY_FLG                        389320 non-null  int64
 31  EXPENSIVE_FLG                    389320 non-null  int64
 32  SPECIAL_DIV                      389320 non-null  int64
 33  ACTUAL_SHIP_DAYS                 389320 non-null  int64
 34  SPECIFY_PRODUCTION_DAYS          389320 non-null  int64
 35  SPECIFY_SHIP_DAYS                389320 non-null  int64
 36  HAZARD_FLG                       389320 non-null  int64
 37  SO_DAY_OF_MONTH                  389320 non-null  int64
 38  SO_DAY_OF_WEEK                   389320 non-null  int64
 39  IO_UNFIT_FLG                     389320 non-null  int64
 40  WEIGHT_UNIT                      387533 non-null  object
 41  REASON_CD                        389320 non-null  object
 42  SOUF_RCV_NO                      14256 non-null   object
 43  QTUF_RCV_NO                      561 non-null     float64
 44  SO_TIME                          389320 non-null  int64
 45  SUPPLIER_CATEGORY_CD             389320 non-null  int64
 46  PRODUCT_ASSORT                   389320 non-null  object
dtypes: float64(5), int64(26), object(16)
memory usage: 139.6+ MB
None
============================================================
delay_7_9
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26217 entries, 0 to 26216
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Order date                       26217 non-null  object
 1   SUBSIDIARY_CD                    26217 non-null  object
 2   GLOBAL_NO                        26217 non-null  object
 3   CLASSIFY_CD                      26217 non-null  int64
 4   CUST_CD                          26217 non-null  int64
 5   BRAND_CD                         26217 non-null  object
 6   INNER_CD                         26217 non-null  object
 7   SUPPLIER_CD                      26217 non-null  object
 8   Sales order line number          26217 non-null  int64
 9   Stock class                      26217 non-null  int64
 10  Consider count hodiday Saturday  26217 non-null  int64
 11  SO QTY                           26217 non-null  int64
 12  OTHER AREA SHIP DIV              5998 non-null   float64
 13  ALLOCATION QTY                   26217 non-null  int64
 14  SUPPLIER INV AMOUNT              26217 non-null  float64
 15  PACKING RANK                     26217 non-null  object
 16  PRODUCT_CD                       26217 non-null  object
 17  PRODUCT ATTRIBUTION              26217 non-null  int64
 18  SPECIAL DIV                      26217 non-null  int64
 19  LOGICAL PLANT                    26217 non-null  int64
 20  PURCHASE AMOUNT                  26217 non-null  float64
 21  VSD                              26217 non-null  object
 22  DIRECT SHIP FLG                  26217 non-null  int64
 23  DELI_DIV                         26217 non-null  object
 24  label                            26217 non-null  int64
 25  Ship Mode                        25733 non-null  object
 26  SHIP DECISION NO                 25456 non-null  float64
 27  PACK QTY                         26217 non-null  int64
 28  WEIGHT PER PIECE                 26217 non-null  int64
 29  SUPPLIER_DIV                     26217 non-null  float64
 30  SPECIAL_DIV                      26217 non-null  int64
 31  SO_DAY_OF_MONTH                  26217 non-null  int64
 32  SO_DAY_OF_WEEK                   26217 non-null  int64
 33  REASON_CD                        22521 non-null  float64
 34  SOUF_RCV_NO                      1269 non-null   object
 35  QTUF_RCV_NO                      84 non-null     float64
 36  SO_TIME                          26217 non-null  int64
dtypes: float64(7), int64(18), object(12)
memory usage: 7.4+ MB
None
============================================================
not_delay_7_9
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048680 entries, 0 to 1048679
Data columns (total 37 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Order date                       1048680 non-null  object
 1   SUBSIDIARY_CD                    1048680 non-null  object
 2   GLOBAL_NO                        1048680 non-null  object
 3   CLASSIFY_CD                      1048680 non-null  int64
 4   CUST_CD                          1048680 non-null  int64
 5   BRAND_CD                         1048680 non-null  object
 6   INNER_CD                         1048680 non-null  object
 7   SUPPLIER_CD                      1048680 non-null  object
 8   Sales order line number          1048680 non-null  int64
 9   Stock class                      1048680 non-null  int64
 10  Consider count hodiday Saturday  1048680 non-null  int64
 11  SO QTY                           1048680 non-null  int64
 12  OTHER AREA SHIP DIV              156645 non-null   float64
 13  ALLOCATION QTY                   1048680 non-null  int64
 14  SUPPLIER INV AMOUNT              1048680 non-null  float64
 15  PACKING RANK                     1048680 non-null  object
 16  PRODUCT_CD                       1048680 non-null  object
 17  PRODUCT ATTRIBUTION              1048680 non-null  int64
 18  SPECIAL DIV                      1048680 non-null  int64
 19  LOGICAL PLANT                    1048680 non-null  int64
 20  PURCHASE AMOUNT                  1048680 non-null  float64
 21  VSD                              1048680 non-null  object
 22  DIRECT SHIP FLG                  1048680 non-null  int64
 23  DELI_DIV                         1048680 non-null  object
 24  label                            1048680 non-null  int64
 25  Ship Mode                        1034672 non-null  object
 26  SHIP DECISION NO                 978027 non-null   float64
 27  PACK QTY                         1048680 non-null  int64
 28  WEIGHT PER PIECE                 1048680 non-null  int64
 29  SUPPLIER_DIV                     1048672 non-null  float64
 30  SPECIAL_DIV                      1048680 non-null  int64
 31  SO_DAY_OF_MONTH                  1048680 non-null  int64
 32  SO_DAY_OF_WEEK                   1048680 non-null  int64
 33  REASON_CD                        19362 non-null    float64
 34  SOUF_RCV_NO                      35222 non-null    object
 35  QTUF_RCV_NO                      1261 non-null     float64
 36  SO_TIME                          1048680 non-null  int64
dtypes: float64(7), int64(18), object(12)
memory usage: 296.0+ MB
None

## Đếm số lượng missing value

In [9]:
for name, df in datasets.items():

    print("=" * 60)
    print(name)
    print("=" * 60)

    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    print(missing)

============================================================
delay_4_6
============================================================
QTUF_RCV_NO         9701
SOUF_RCV_NO         9147
Ship Mode            481
SHIP DECISION NO      91
WEIGHT_UNIT           90
dtype: int64
============================================================
not_delay_4_6
============================================================
QTUF_RCV_NO         388759
SOUF_RCV_NO         375064
SHIP DECISION NO     33226
Ship Mode             6107
WEIGHT_UNIT           1787
SUPPLIER_DIV             4
dtype: int64
============================================================
delay_7_9
============================================================
QTUF_RCV_NO            26133
SOUF_RCV_NO            24948
OTHER AREA SHIP DIV    20219
REASON_CD               3696
SHIP DECISION NO         761
Ship Mode                484
dtype: int64
============================================================
not_delay_7_9
============================================================
QTUF_RCV_NO            1047419
REASON_CD              1029318
SOUF_RCV_NO            1013458
OTHER AREA SHIP DIV     892035
SHIP DECISION NO         70653
Ship Mode                14008
SUPPLIER_DIV                 8
dtype: int64

## Kiểm tra có hàng bị trùng không

In [10]:
for name, df in datasets.items():

    print(f"{name}: {df.duplicated().sum()} duplicated rows")

delay_4_6: 0 duplicated rows
not_delay_4_6: 0 duplicated rows
delay_7_9: 0 duplicated rows
not_delay_7_9: 0 duplicated rows

## Check schema

In [11]:
print("delay_4_6 vs not_delay_4_6:")
print(set(delay_4_6.columns) == set(not_delay_4_6.columns))

print("\ndelay_7_9 vs not_delay_7_9:")
print(set(delay_7_9.columns) == set(not_delay_7_9.columns))

print("\ndelay_4_6 vs delay_7_9:")
print(set(delay_4_6.columns) == set(delay_7_9.columns))

print("\nnot_delay_4_6 vs not_delay_7_9:")
print(set(not_delay_4_6.columns) == set(not_delay_7_9.columns))

delay_4_6 vs not_delay_4_6:
True

delay_7_9 vs not_delay_7_9:
True

delay_4_6 vs delay_7_9:
False

not_delay_4_6 vs not_delay_7_9:
False

In [12]:
print("Columns only in delay_4_6:")
print(set(delay_4_6.columns) - set(delay_7_9.columns))

print("\nColumns only in delay_7_9:")
print(set(delay_7_9.columns) - set(delay_4_6.columns))


print("\nColumns only in not_delay_4_6:")
print(set(not_delay_4_6.columns) - set(not_delay_7_9.columns))

print("\nColumns only in not_delay_7_9:")
print(set(not_delay_7_9.columns) - set(not_delay_4_6.columns))

Columns only in delay_4_6:
{'EXPENSIVE_FLG', 'SPECIFY_PRODUCTION_DAYS', 'SUPPLIER_CATEGORY_CD', 'HEAVY_FLG', 'WEIGHT_UNIT', 'SPECIFY_SHIP_DAYS', 'HAZARD_FLG', 'ACTUAL_SHIP_DAYS', 'IO_UNFIT_FLG', 'PRODUCT_ASSORT'}

Columns only in delay_7_9:
set()

Columns only in not_delay_4_6:
{'EXPENSIVE_FLG', 'SPECIFY_PRODUCTION_DAYS', 'SUPPLIER_CATEGORY_CD', 'HEAVY_FLG', 'WEIGHT_UNIT', 'SPECIFY_SHIP_DAYS', 'HAZARD_FLG', 'ACTUAL_SHIP_DAYS', 'IO_UNFIT_FLG', 'PRODUCT_ASSORT'}

Columns only in not_delay_7_9:
set()

## Kiểm tra số lượng cột dữ liệu số

In [13]:
for name, df in datasets.items():

    num_cols = df.select_dtypes(include=np.number).columns
    cat_cols = df.select_dtypes(exclude=np.number).columns

    print("=" * 60)
    print(name)

    print("Numerical columns:", len(num_cols))
    print("Categorical columns:", len(cat_cols))

    print("\n")

============================================================
delay_4_6
Numerical columns: 32
Categorical columns: 15


============================================================
not_delay_4_6
Numerical columns: 31
Categorical columns: 16


============================================================
delay_7_9
Numerical columns: 25
Categorical columns: 12


============================================================
not_delay_7_9
Numerical columns: 25
Categorical columns: 12

In [14]:
for name, df in datasets.items():

    num_cols = df.select_dtypes(include=np.number).columns

    print("=" * 60)
    print(name)

    print(list(num_cols))

    print("\n")

============================================================
delay_4_6
['GLOBAL_NO', 'CLASSIFY_CD', 'CUST_CD', 'Sales order line number', 'Stock class', 'Consider count hodiday Saturday', 'SO QTY', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'SPECIAL DIV', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'HEAVY_FLG', 'EXPENSIVE_FLG', 'SPECIAL_DIV', 'ACTUAL_SHIP_DAYS', 'SPECIFY_PRODUCTION_DAYS', 'SPECIFY_SHIP_DAYS', 'HAZARD_FLG', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'IO_UNFIT_FLG', 'QTUF_RCV_NO', 'SO_TIME', 'SUPPLIER_CATEGORY_CD']


============================================================
not_delay_4_6
['GLOBAL_NO', 'CLASSIFY_CD', 'CUST_CD', 'Sales order line number', 'Stock class', 'SO QTY', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'SPECIAL DIV', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'HEAVY_FLG', 'EXPENSIVE_FLG', 'SPECIAL_DIV', 'ACTUAL_SHIP_DAYS', 'SPECIFY_PRODUCTION_DAYS', 'SPECIFY_SHIP_DAYS', 'HAZARD_FLG', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'IO_UNFIT_FLG', 'QTUF_RCV_NO', 'SO_TIME', 'SUPPLIER_CATEGORY_CD']


============================================================
delay_7_9
['CLASSIFY_CD', 'CUST_CD', 'Sales order line number', 'Stock class', 'Consider count hodiday Saturday', 'SO QTY', 'OTHER AREA SHIP DIV', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'SPECIAL DIV', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'SPECIAL_DIV', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'REASON_CD', 'QTUF_RCV_NO', 'SO_TIME']


============================================================
not_delay_7_9
['CLASSIFY_CD', 'CUST_CD', 'Sales order line number', 'Stock class', 'Consider count hodiday Saturday', 'SO QTY', 'OTHER AREA SHIP DIV', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'SPECIAL DIV', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'SPECIAL_DIV', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'REASON_CD', 'QTUF_RCV_NO', 'SO_TIME']

In [15]:
for name, df in datasets.items():

    num_cols = df.select_dtypes(include=np.number).columns

    print("=" * 60)
    print(name)

    for col in num_cols:

        negative_count = (df[col] < 0).sum()

        if negative_count > 0:
            print(f"{col}: {negative_count} negative values")

    print("\n")

============================================================
delay_4_6
SPECIFY_PRODUCTION_DAYS: 9688 negative values
SPECIFY_SHIP_DAYS: 9667 negative values


============================================================
not_delay_4_6
SPECIFY_PRODUCTION_DAYS: 388616 negative values
SPECIFY_SHIP_DAYS: 388090 negative values


============================================================
delay_7_9


============================================================
not_delay_7_9

## Kiểm tra dữ liệu categorical

In [16]:
for name, df in datasets.items():

    cat_cols = df.select_dtypes(exclude=np.number).columns

    print("=" * 60)
    print(name)

    print(list(cat_cols))

    print("\n")

============================================================
delay_4_6
['Order date', 'SUBSIDIARY_CD', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'OTHER AREA SHIP DIV', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode', 'WEIGHT_UNIT', 'REASON_CD', 'SOUF_RCV_NO', 'PRODUCT_ASSORT']


============================================================
not_delay_4_6
['Order date', 'SUBSIDIARY_CD', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'Consider count hodiday Saturday', 'OTHER AREA SHIP DIV', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode', 'WEIGHT_UNIT', 'REASON_CD', 'SOUF_RCV_NO', 'PRODUCT_ASSORT']


============================================================
delay_7_9
['Order date', 'SUBSIDIARY_CD', 'GLOBAL_NO', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode', 'SOUF_RCV_NO']


============================================================
not_delay_7_9
['Order date', 'SUBSIDIARY_CD', 'GLOBAL_NO', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode', 'SOUF_RCV_NO']

In [17]:
for name, df in datasets.items():

    cat_cols = df.select_dtypes(exclude=np.number).columns

    print("=" * 60)
    print(name)

    for col in cat_cols:

        whitespace_count = (
            df[col]
            .astype(str)
            .str.strip()
            .eq("")
            .sum()
        )

        if whitespace_count > 0:
            print(f"{col}: {whitespace_count} whitespace values")

    print("\n")

============================================================
delay_4_6
OTHER AREA SHIP DIV: 6748 whitespace values
REASON_CD: 5047 whitespace values
PRODUCT_ASSORT: 9733 whitespace values


============================================================
not_delay_4_6
Consider count hodiday Saturday: 1 whitespace values
OTHER AREA SHIP DIV: 326654 whitespace values
REASON_CD: 373795 whitespace values
PRODUCT_ASSORT: 389320 whitespace values


============================================================
delay_7_9


============================================================
not_delay_7_9

## Kiểm tra unique

In [18]:
for name, df in datasets.items():

    print("=" * 60)
    print(name)

    unique_counts = df.nunique().sort_values()

    print(unique_counts.head(20))

    print("\n")

============================================================
delay_4_6
SUBSIDIARY_CD                      1
label                              1
HAZARD_FLG                         1
IO_UNFIT_FLG                       1
WEIGHT_UNIT                        1
PRODUCT_ASSORT                     1
OTHER AREA SHIP DIV                2
Stock class                        2
HEAVY_FLG                          2
DIRECT SHIP FLG                    2
PRODUCT ATTRIBUTION                2
SPECIAL_DIV                        2
SPECIAL DIV                        2
EXPENSIVE_FLG                      2
Consider count hodiday Saturday    3
LOGICAL PLANT                      3
SUPPLIER_DIV                       4
DELI_DIV                           5
SUPPLIER_CATEGORY_CD               5
SO_DAY_OF_WEEK                     6
dtype: int64


============================================================
not_delay_4_6
SUBSIDIARY_CD                      1
label                              1
WEIGHT_UNIT                        1
HAZARD_FLG                         1
PRODUCT_ASSORT                     1
SPECIAL DIV                        2
OTHER AREA SHIP DIV                2
Stock class                        2
HEAVY_FLG                          2
DIRECT SHIP FLG                    2
PRODUCT ATTRIBUTION                2
IO_UNFIT_FLG                       2
SPECIAL_DIV                        2
EXPENSIVE_FLG                      2
LOGICAL PLANT                      3
SUPPLIER_DIV                       4
SUPPLIER_CATEGORY_CD               5
Consider count hodiday Saturday    5
SO_DAY_OF_WEEK                     6
PACKING RANK                       7
dtype: int64


============================================================
delay_7_9
SUBSIDIARY_CD                       1
OTHER AREA SHIP DIV                 1
label                               1
Stock class                         2
SPECIAL DIV                         2
DIRECT SHIP FLG                     2
PRODUCT ATTRIBUTION                 2
SPECIAL_DIV                         2
LOGICAL PLANT                       3
SUPPLIER_DIV                        4
Consider count hodiday Saturday     4
SO_DAY_OF_WEEK                      6
PACKING RANK                        7
DELI_DIV                            7
Ship Mode                          18
SO_DAY_OF_MONTH                    31
REASON_CD                          40
PACK QTY                           67
Order date                         79
QTUF_RCV_NO                        84
dtype: int64


============================================================
not_delay_7_9
SUBSIDIARY_CD                        1
OTHER AREA SHIP DIV                  1
label                                1
Stock class                          2
SPECIAL DIV                          2
DIRECT SHIP FLG                      2
PRODUCT ATTRIBUTION                  2
SPECIAL_DIV                          2
LOGICAL PLANT                        3
SUPPLIER_DIV                         4
Consider count hodiday Saturday      4
SO_DAY_OF_WEEK                       6
PACKING RANK                         7
DELI_DIV                            10
Ship Mode                           20
SO_DAY_OF_MONTH                     31
REASON_CD                           58
Order date                          79
PACK QTY                           174
VSD                                382
dtype: int64

# Chuẩn hóa schema

## Đưa cột về cùng 1 thứ tự

In [19]:
not_delay_4_6 = not_delay_4_6[delay_4_6.columns]
not_delay_7_9 = not_delay_7_9[delay_7_9.columns]

## Xét tháng 4-6

### Kiểm tra coi dữ liệu delay và not_delay trong tháng 4-6 đã giống nhau chưa

In [20]:
print("Dtypes in delay_4_6")
print(delay_4_6.dtypes)

print("\nDtypes in not_delay_4_6")
print(not_delay_4_6.dtypes)

Dtypes in delay_4_6
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                            int64
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday      int64
SO QTY                               int64
OTHER AREA SHIP DIV                 object
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
HEAVY_FLG                            int64
EXPENSIVE_FLG                        int64
SPECIAL_DIV                          int64
ACTUAL_SHIP_DAYS                     int64
SPECIFY_PRODUCTION_DAYS              int64
SPECIFY_SHIP_DAYS                    int64
HAZARD_FLG                           int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
IO_UNFIT_FLG                         int64
WEIGHT_UNIT                         object
REASON_CD                           object
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
SUPPLIER_CATEGORY_CD                 int64
PRODUCT_ASSORT                      object
dtype: object

Dtypes in not_delay_4_6
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                            int64
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday     object
SO QTY                               int64
OTHER AREA SHIP DIV                 object
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
HEAVY_FLG                            int64
EXPENSIVE_FLG                        int64
SPECIAL_DIV                          int64
ACTUAL_SHIP_DAYS                     int64
SPECIFY_PRODUCTION_DAYS              int64
SPECIFY_SHIP_DAYS                    int64
HAZARD_FLG                           int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
IO_UNFIT_FLG                         int64
WEIGHT_UNIT                         object
REASON_CD                           object
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
SUPPLIER_CATEGORY_CD                 int64
PRODUCT_ASSORT                      object
dtype: object

In [21]:
dtype_compare = pd.DataFrame({
    "delay_4_6": delay_4_6.dtypes,
    "not_delay_4_6": not_delay_4_6.dtypes
})

dtype_compare[
    dtype_compare["delay_4_6"] != dtype_compare["not_delay_4_6"]
]

                                delay_4_6 not_delay_4_6
Consider count hodiday Saturday     int64        object

### Fix đều đưa về int64

In [ ]:
col = "Consider count hodiday Saturday"

delay_4_6[col] = delay_4_6[col].astype("Int64")
not_delay_4_6[col] = not_delay_4_6[col].astype("Int64")

ValueError: invalid literal for int() with base 10: ' '

:

In [ ]:
print(
    delay_4_6["Consider count hodiday Saturday"].dtype
)

print(
    not_delay_4_6["Consider count hodiday Saturday"].dtype
)

Int64
Int64

### Check shape

In [ ]:
print("delay_4_6 shape:")
print(delay_4_6.shape)
print("not_delay_4_6 shape:")
print(not_delay_4_6.shape)

delay_4_6 shape:
(9733, 47)
not_delay_4_6 shape:
(389320, 47)

### Merge lại tháng 4-6

In [ ]:
df_4_6 = pd.concat(
    [delay_4_6, not_delay_4_6],
    ignore_index=True
)

In [ ]:
expected_rows = delay_4_6.shape[0] + not_delay_4_6.shape[0]

print("Expected rows:", expected_rows)
print("Actual rows:", df_4_6.shape[0])

Expected rows: 399053
Actual rows: 399053

In [ ]:
print(df_4_6["label"].value_counts())

label
0    389320
1      9733
Name: count, dtype: int64

## Xét tháng 7-9

### Xét kiểu dữ liệu coi đồng nhất chưa

In [ ]:
print("Dtypes in delay_4_6")
print(delay_4_6.dtypes)

print("\nDtypes in not_delay_4_6")
print(not_delay_4_6.dtypes)

Dtypes in delay_4_6
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                            int64
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday      Int64
SO QTY                               int64
OTHER AREA SHIP DIV                 object
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
HEAVY_FLG                            int64
EXPENSIVE_FLG                        int64
SPECIAL_DIV                          int64
ACTUAL_SHIP_DAYS                     int64
SPECIFY_PRODUCTION_DAYS              int64
SPECIFY_SHIP_DAYS                    int64
HAZARD_FLG                           int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
IO_UNFIT_FLG                         int64
WEIGHT_UNIT                         object
REASON_CD                           object
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
SUPPLIER_CATEGORY_CD                 int64
PRODUCT_ASSORT                      object
dtype: object

Dtypes in not_delay_4_6
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                            int64
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday      Int64
SO QTY                               int64
OTHER AREA SHIP DIV                 object
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
HEAVY_FLG                            int64
EXPENSIVE_FLG                        int64
SPECIAL_DIV                          int64
ACTUAL_SHIP_DAYS                     int64
SPECIFY_PRODUCTION_DAYS              int64
SPECIFY_SHIP_DAYS                    int64
HAZARD_FLG                           int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
IO_UNFIT_FLG                         int64
WEIGHT_UNIT                         object
REASON_CD                           object
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
SUPPLIER_CATEGORY_CD                 int64
PRODUCT_ASSORT                      object
dtype: object

In [ ]:
dtype_compare_7_9 = pd.DataFrame({
    "delay_7_9": delay_7_9.dtypes,
    "not_delay_7_9": not_delay_7_9.dtypes
})

display(
    dtype_compare_7_9[
        dtype_compare_7_9["delay_7_9"] != dtype_compare_7_9["not_delay_7_9"]
    ]
)

Empty DataFrame
Columns: [delay_7_9, not_delay_7_9]
Index: []

### Check shape trước khi merge

In [ ]:
df_7_9 = pd.concat(
    [delay_7_9, not_delay_7_9],
    ignore_index=True
)

In [ ]:
expected_rows = (
    delay_7_9.shape[0]
    + not_delay_7_9.shape[0]
)

print("Expected rows:", expected_rows)
print("Actual rows:", df_7_9.shape[0])

Expected rows: 1074897
Actual rows: 1074897

### Check phân phối nhãn

In [ ]:
print(df_7_9["label"].value_counts())

label
0    1048680
1      26217
Name: count, dtype: int64

# Cleaning

In [ ]:
def standardize_text_columns(df):
    df = df.copy()
    for col in df.select_dtypes(include=["object", "string"]).columns:
        df[col] = df[col].astype("string").str.strip()
        df[col] = df[col].replace({
            "": pd.NA,
            "nan": pd.NA,
            "NaN": pd.NA,
            "None": pd.NA
        })
    return df


def fill_with_mode(df, cols):
    df = df.copy()
    for col in cols:
        if col in df.columns and df[col].isna().any():
            mode_value = df[col].mode(dropna=True)
            if len(mode_value) > 0:
                df[col] = df[col].fillna(mode_value.iloc[0])
    return df


def drop_high_missing(df, threshold=0.95, exclude=None):
    df = df.copy()
    exclude = set(exclude or [])
    missing_ratio = df.isna().mean()
    drop_cols = [
        c for c, r in missing_ratio.items()
        if r >= threshold and c not in exclude and c != "label"
    ]
    df = df.drop(columns=drop_cols, errors="ignore")
    return df, drop_cols, missing_ratio


def drop_constant_cols(df):
    df = df.copy()
    constant_cols = [
        c for c in df.columns
        if c != "label" and df[c].nunique(dropna=False) <= 1
    ]
    df = df.drop(columns=constant_cols, errors="ignore")
    return df, constant_cols

## Với dataset từ tháng 4 tới tháng 6

In [ ]:
df_4_6_tidy = df_4_6.copy()
df_4_6_tidy = standardize_text_columns(df_4_6_tidy)

In [ ]:
if "Consider count hodiday Saturday" in df_4_6_tidy.columns:
    df_4_6_tidy["Consider count hodiday Saturday"] = (
        pd.to_numeric(df_4_6_tidy["Consider count hodiday Saturday"], errors="coerce")
        .fillna(0)
        .astype("Int64")
    )
if "OTHER AREA SHIP DIV" in df_4_6_tidy.columns:
    df_4_6_tidy["OTHER AREA SHIP DIV"] = df_4_6_tidy["OTHER AREA SHIP DIV"].fillna("0")

In [ ]:
df_4_6_tidy, dropped_missing_4_6, missing_ratio_4_6 = drop_high_missing(
    df_4_6_tidy,
    threshold=0.95,
    exclude=["OTHER AREA SHIP DIV", "Ship Mode", "SHIP DECISION NO", "SUPPLIER_DIV"]
)

print("Dropped because of high missing ratio (4_6):")
print(dropped_missing_4_6)

Dropped because of high missing ratio (4_6):
['SOUF_RCV_NO', 'QTUF_RCV_NO', 'PRODUCT_ASSORT']

In [ ]:
df_4_6_tidy, constant_cols_4_6 = drop_constant_cols(df_4_6_tidy)

print("Dropped constant columns (4_6):")
print(constant_cols_4_6)

Dropped constant columns (4_6):
['SUBSIDIARY_CD', 'HAZARD_FLG']

In [ ]:
if {"SPECIAL DIV", "SPECIAL_DIV"}.issubset(df_4_6_tidy.columns):
    if df_4_6_tidy["SPECIAL DIV"].equals(df_4_6_tidy["SPECIAL_DIV"]):
        df_4_6_tidy = df_4_6_tidy.drop(columns=["SPECIAL DIV"])

In [ ]:
display(
    df_4_6_tidy.isna().sum()
    .sort_values(ascending=False)
    [df_4_6_tidy.isna().sum().sort_values(ascending=False) > 0]
)

REASON_CD           378842
SHIP DECISION NO     33317
Ship Mode             6588
WEIGHT_UNIT           1877
SUPPLIER_DIV             4
dtype: int64

## Với tháng 7 - 9

In [ ]:
df_7_9_tidy = df_7_9.copy()
df_7_9_tidy = standardize_text_columns(df_7_9_tidy)

In [ ]:
if "Consider count hodiday Saturday" in df_7_9_tidy.columns:
    df_7_9_tidy["Consider count hodiday Saturday"] = (
        pd.to_numeric(df_7_9_tidy["Consider count hodiday Saturday"], errors="coerce")
        .fillna(0)
        .astype("Int64")
    )

In [ ]:
if "OTHER AREA SHIP DIV" in df_7_9_tidy.columns:
    df_7_9_tidy["OTHER AREA SHIP DIV"] = df_7_9_tidy["OTHER AREA SHIP DIV"].fillna("0")

In [ ]:
df_7_9_tidy, dropped_missing_7_9, missing_ratio_7_9 = drop_high_missing(
    df_7_9_tidy,
    threshold=0.95,
    exclude=["OTHER AREA SHIP DIV", "Ship Mode", "SHIP DECISION NO", "SUPPLIER_DIV"]
)

print("Dropped because of high missing ratio (7_9):")
print(dropped_missing_7_9)

Dropped because of high missing ratio (7_9):
['REASON_CD', 'SOUF_RCV_NO', 'QTUF_RCV_NO']

In [ ]:
df_7_9_tidy, constant_cols_7_9 = drop_constant_cols(df_7_9_tidy)

print("Dropped constant columns (7_9):")
print(constant_cols_7_9)

Dropped constant columns (7_9):
['SUBSIDIARY_CD']

In [ ]:
if {"SPECIAL DIV", "SPECIAL_DIV"}.issubset(df_7_9_tidy.columns):
    if df_7_9_tidy["SPECIAL DIV"].equals(df_7_9_tidy["SPECIAL_DIV"]):
        df_7_9_tidy = df_7_9_tidy.drop(columns=["SPECIAL DIV"])

In [ ]:
df_7_9_tidy = fill_with_mode(df_7_9_tidy, ["Ship Mode", "SHIP DECISION NO", "SUPPLIER_DIV"])

In [ ]:
before_dup_7_9 = df_7_9_tidy.shape[0]
df_7_9_tidy = df_7_9_tidy.drop_duplicates()
after_dup_7_9 = df_7_9_tidy.shape[0]

print("Rows removed by duplicate dropping (7_9):", before_dup_7_9 - after_dup_7_9)
print("Shape after cleaning (7_9):", df_7_9_tidy.shape)

Rows removed by duplicate dropping (7_9): 0
Shape after cleaning (7_9): (1074897, 32)

In [ ]:
display(
    df_7_9_tidy.isna().sum()
    .sort_values(ascending=False)
    [df_7_9_tidy.isna().sum().sort_values(ascending=False) > 0]
)

Series([], dtype: int64)

# Type conversion

In [ ]:
def convert_datetime_cols(df, cols):
    df = df.copy()
    for col in cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
    return df


def convert_string_cols(df, cols):
    df = df.copy()
    for col in cols:
        if col in df.columns:
            df[col] = df[col].astype("string")
    return df

## Tháng 4-6

In [ ]:
df_4_6_tidy = convert_datetime_cols(df_4_6_tidy, ["Order date"])

id_like_cols_4_6 = [
    "SUBSIDIARY_CD",
    "GLOBAL_NO",
    "CLASSIFY_CD",
    "CUST_CD",
    "BRAND_CD",
    "INNER_CD",
    "SUPPLIER_CD",
    "Sales order line number",
    "PACKING RANK",
    "PRODUCT_CD",
    "VSD",
    "DELI_DIV",
    "Ship Mode",
    "WEIGHT_UNIT",
    "REASON_CD",
    "SOUF_RCV_NO",
    "PRODUCT_ASSORT"
]

df_4_6_tidy = convert_string_cols(df_4_6_tidy, id_like_cols_4_6)

## Tháng 7-9

In [ ]:
df_7_9_tidy = convert_datetime_cols(df_7_9_tidy, ["Order date"])

id_like_cols_7_9 = [
    "SUBSIDIARY_CD",
    "GLOBAL_NO",
    "CLASSIFY_CD",
    "CUST_CD",
    "BRAND_CD",
    "INNER_CD",
    "SUPPLIER_CD",
    "Sales order line number",
    "PACKING RANK",
    "PRODUCT_CD",
    "VSD",
    "DELI_DIV",
    "Ship Mode",
    "SOUF_RCV_NO",
    "REASON_CD"
]

df_7_9_tidy = convert_string_cols(df_7_9_tidy, id_like_cols_7_9)

## Chia nhóm date/time, num, cate

In [ ]:
def split_column_types(df):
    date_cols = df.select_dtypes(include=["datetime64[ns]", "datetimetz"]).columns.tolist()
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    cat_cols = df.select_dtypes(include=["object", "string", "category"]).columns.tolist()
    
    return date_cols, num_cols, cat_cols

In [ ]:
date_cols_4_6, num_cols_4_6, cat_cols_4_6 = split_column_types(df_4_6_tidy)

print("df_4_6_tidy")
print("Date columns:", len(date_cols_4_6))
print("Numeric columns:", len(num_cols_4_6))
print("Categorical columns:", len(cat_cols_4_6))

print("\nDate cols:", date_cols_4_6)
print("\nNumeric cols:", num_cols_4_6)
print("\nCategorical cols:", cat_cols_4_6)

df_4_6_tidy
Date columns: 1
Numeric columns: 25
Categorical columns: 15

Date cols: ['Order date']

Numeric cols: ['Stock class', 'Consider count hodiday Saturday', 'SO QTY', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'HEAVY_FLG', 'EXPENSIVE_FLG', 'SPECIAL_DIV', 'ACTUAL_SHIP_DAYS', 'SPECIFY_PRODUCTION_DAYS', 'SPECIFY_SHIP_DAYS', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'IO_UNFIT_FLG', 'SO_TIME', 'SUPPLIER_CATEGORY_CD']

Categorical cols: ['GLOBAL_NO', 'CLASSIFY_CD', 'CUST_CD', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'Sales order line number', 'OTHER AREA SHIP DIV', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode', 'WEIGHT_UNIT', 'REASON_CD']

In [ ]:
date_cols_7_9, num_cols_7_9, cat_cols_7_9 = split_column_types(df_7_9_tidy)

print("df_7_9_tidy")
print("Date columns:", len(date_cols_7_9))
print("Numeric columns:", len(num_cols_7_9))
print("Categorical columns:", len(cat_cols_7_9))

print("\nDate cols:", date_cols_7_9)
print("\nNumeric cols:", num_cols_7_9)
print("\nCategorical cols:", cat_cols_7_9)

df_7_9_tidy
Date columns: 1
Numeric columns: 18
Categorical columns: 13

Date cols: ['Order date']

Numeric cols: ['Stock class', 'Consider count hodiday Saturday', 'SO QTY', 'ALLOCATION QTY', 'SUPPLIER INV AMOUNT', 'PRODUCT ATTRIBUTION', 'LOGICAL PLANT', 'PURCHASE AMOUNT', 'DIRECT SHIP FLG', 'label', 'SHIP DECISION NO', 'PACK QTY', 'WEIGHT PER PIECE', 'SUPPLIER_DIV', 'SPECIAL_DIV', 'SO_DAY_OF_MONTH', 'SO_DAY_OF_WEEK', 'SO_TIME']

Categorical cols: ['GLOBAL_NO', 'CLASSIFY_CD', 'CUST_CD', 'BRAND_CD', 'INNER_CD', 'SUPPLIER_CD', 'Sales order line number', 'OTHER AREA SHIP DIV', 'PACKING RANK', 'PRODUCT_CD', 'VSD', 'DELI_DIV', 'Ship Mode']

# Đánh giá lại dữ liệu cuối cùng

In [ ]:
print("df_4_6_tidy")

total_cells = df_4_6_tidy.shape[0] * df_4_6_tidy.shape[1]
missing_values = df_4_6_tidy.isna().sum().sum()
missing_ratio = missing_values / total_cells

print("Shape:", df_4_6_tidy.shape)
print("Missing ratio:", round(missing_ratio * 100, 4), "%")
print("Duplicate rows:", df_4_6_tidy.duplicated().sum())
print("Duplicate columns:", df_4_6_tidy.columns.duplicated().sum())

print(
    "Is clean:",
    missing_ratio < 0.03
    and df_4_6_tidy.duplicated().sum() == 0
    and df_4_6_tidy.columns.duplicated().sum() == 0
)

df_4_6_tidy
Shape: (399053, 41)
Missing ratio: 2.5709 %
Duplicate rows: 0
Duplicate columns: 0
Is clean: True

In [ ]:
print("df_7_9_tidy")

total_cells = df_7_9_tidy.shape[0] * df_7_9_tidy.shape[1]
missing_values = df_7_9_tidy.isna().sum().sum()
missing_ratio = missing_values / total_cells

print("Shape:", df_7_9_tidy.shape)
print("Missing values:", missing_values)
print("Missing ratio:", round(missing_ratio * 100, 4), "%")
print("Duplicate rows:", df_7_9_tidy.duplicated().sum())
print("Duplicate columns:", df_7_9_tidy.columns.duplicated().sum())

print(
    "Is clean:",
    missing_ratio < 0.01
    and df_7_9_tidy.duplicated().sum() == 0
    and df_7_9_tidy.columns.duplicated().sum() == 0
)

df_7_9_tidy
Shape: (1074897, 32)
Missing values: 0
Missing ratio: 0.0 %
Duplicate rows: 0
Duplicate columns: 0
Is clean: True

# Lưu file

In [ ]:
df_4_6_tidy.to_csv("df_4_6_tidy.csv", index=False)
df_7_9_tidy.to_csv("df_7_9_tidy.csv", index=False)

print("Saved:")
print("- df_4_6_tidy.csv")
print("- df_7_9_tidy.csv")

Saved:
- df_4_6_tidy.csv
- df_7_9_tidy.csv